export const IS_WORLD_LOADING_SUCCESS = "IS_WORLD_LOADING_SUCCESS";
export const IS_UKRAINE_LOADING_SUCCESS = "IS_UKRAINE_LOADING_SUCCESS";
export const SET_STATISTICS_START = "SET_STATISTICS_START";
export const IS_ERROR = "IS-ERROR";
